### PR TITLE
Add deployment instructions, and release script

### PR DESCRIPTION
**Pull request by birkholz**
* Adds a script for easily deploying new versions to PyPi
* Updates the README with deployment instructions

screen shot 2016-12-06 at 3 16 09 pm

### CODE REVIEW

**Comment by birkholz** [comment]
[Update the zc_common README with an explanation of deployment](https://trello.com/c/htfLx3Ox/208-update-the-zc-common-readme-with-an-explanation-of-deployment)

**Comment by birkholz** [comment]
@rfadams Not exactly, because the version bump has to be committed to master. So although the script could change the file, it shouldn't be in the business of making commits or touching master (bypassing PRs)

**Comment by tpilara** [comment]
The content looks good. As we add additional libraries though (`zc_events` being the most recent one) I feel like this might be more appropriate to go into mp-planning so we don't need to duplicate this explanation in each new repo. What do you think?

**Comment by birkholz** [comment]
@tpilara Deployment instructions should always be in the README, as that's where users expect to find such information. I think we could copy it to mp-planning, but it should be here also. Likewise, the script needs to be in this repo, but it could be copied for other libraries, as the script is not specific to this project.

**Comment by tpilara** [comment]
I'm in favor of moving deploy instructions to mp-planning so they only exist in one place with a link and keeping the script here since it is generic and can be run in each repo independently.

**Pull request merged**
