### PR TITLE
Add parsers to support meta data

### PR DESCRIPTION
**Pull request by hamedahmadi**

### CODE REVIEW

**Comment by birkholz** [comment]
A lot of the functionality is copied from [here](https://github.com/django-json-api/django-rest-framework-json-api/blob/develop/rest_framework_json_api/parsers.py#L10)

This parser should be a subclass of the linked parser, with the differences as overrides.

**Comment by birkholz** [comment]
Ignore the above close. Accidental click.

**Comment by hamedahmadi** [comment]
@birkholz 
> This parser should be a subclass of the linked parser, with the differences as overrides.

Good point, but cannot do it unless you know a good way to call super of super! need this [line]
(https://github.com/django-json-api/django-rest-framework-json-api/blob/develop/rest_framework_json_api/parsers.py#L53)

**Comment by birkholz** [comment]
```python
result = JSONParser.parse(self, stream, media_type=media_type, parser_context=parser_context)
```

Just don't call super. Call the method directly from the class, and pass in `self`.

**Comment by hamedahmadi** [comment]
Ah, didn't know you can do it, will push a fix!

**Comment by birkholz** [comment]
It works as long as the first parameter of the function (`self`) is a class instance which has the class in its MRO.

**Comment by birkholz** [comment]
Ultimately, I'd love to see this change as a PR to the JSON API repo, removing the need for this custom parser.

**Comment by birkholz** [comment]
Better 👍

**Comment by hamedahmadi** [comment]
I will make a PR upstream next week, wanna get this stuff out first!

**Pull request merged**
