### PR TITLE
RabbitMQ Event Code

### PR DESCRIPTION
**Pull request by tpilara**
Adds common code for emitting and receiving RabbitMQ events.

### CODE REVIEW

**Comment by tpilara** [comment]
[Create wrapper functions for emitting and listening to events to/from RabbitMQ](https://trello.com/c/Dwx4MANW/1452-create-wrapper-functions-for-emitting-and-listening-to-events-to-from-rabbitmq)

**Comment by tpilara** [comment]
[Create wrapper functions for emitting and listening to events to/from RabbitMQ](https://trello.com/c/Dwx4MANW/1452-create-wrapper-functions-for-emitting-and-listening-to-events-to-from-rabbitmq)

**Comment by hamedahmadi** [comment]
Thanks @tpilara, this looks great! @birkholz can you please review and if it looks good lets create a new version.

@tpilara Add the required things to bump the version

**Comment by tpilara** [comment]
@hamedahmadi Looks like the version is already bumped in master although a new release hasn't been tagged so we may not need to do anything in this PR to get the new version (although the download tarball link in master wasn't bumped)

**Comment by hamedahmadi** [comment]
@tpilara @birkholz I'll leave it to you guys to coordinate the versioning. We probably need to bump again when the S3 stuff is in, but that can be a separate version for itself.

**Comment by birkholz** [comment]
You'll need to bump the version to `0.2.6`.

**Comment by tpilara** [comment]
@birkholz Sorry, for some reason I didn't see that 0.2.5 release tag..I definitely checked. In any case, I'll bump right now.

**Comment by birkholz** [comment]
Haven't reviewed myself, but Hamed says its good. So let's get this deployed.

**Pull request merged**
